# Generated by Django 5.0.1 on 2024-10-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ecomuser_is_verified_ecomuser_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
